###############################################################################
# Bazel now uses Bzlmod by default to manage external dependencies.
# Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel.
#
# For more details, please check https://github.com/bazelbuild/bazel/issues/18958
###############################################################################

module(
    name = "dub",
    version = "0.1",
)

bazel_dep(name = "platforms", version = "0.0.11")
register_toolchains(
    "//toolchain:cc_toolchain_for_linux_x86_64"
)

bazel_dep(name = "rules_python", version = "0.31.0")

bazel_dep(name = "googletest")
git_override(
    module_name = "googletest",
    remote = "https://github.com/google/googletest.git",
    commit = "b75ecf1bed2fcd416b66c86cb6fe79122abf132e",
)

bazel_dep(
    name = "abseil-cpp",
    repo_name = "absl",
)

git_override(
    module_name = "abseil-cpp",
    remote = "https://github.com/abseil/abseil-cpp.git",
    commit = "4358cb2f8cb304e64d9a2d2845f472297724e19f",
)

# bazel_dep(
#     name = "llvm-project",
#     repo_name = "llvm",
#     version = "17.0.3",
# )

# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    commit = "0e990032f3c5a866e72615cf67e5ce22186dcb97",
    #commit = "33658bab23a4858b513d767480b43d3d8fb6a3d1",
    # Even better, set up Renovate and let it do the work for you (see "Suggestion: Updates" in the README).
)
